Imports System.Security.Cryptography
Imports System.Text

Public Class Hashing
    Private DES As New TripleDESCryptoServiceProvider
    Private MD5 As New MD5CryptoServiceProvider

    Public Function MD5Hash(ByVal value As String) As Byte()
        Return MD5.ComputeHash(ASCIIEncoding.ASCII.GetBytes(value))
    End Function

    Public Function Encrypt(ByVal StringToEncrypt As String, ByVal Key As String) As String
        DES.Key = MD5Hash(Key)
        DES.Mode = CipherMode.ECB
        Dim buffer As Byte() = ASCIIEncoding.ASCII.GetBytes(StringToEncrypt)
        Return Convert.ToBase64String(DES.CreateEncryptor().TransformFinalBlock(buffer, 0, buffer.Length))
    End Function

    Public Function Decrypt(ByVal EncryptedString As String, ByVal Key As String) As String
        Try
            DES.Key = MD5Hash(Key)
            DES.Mode = CipherMode.ECB
            Dim buffer As Byte() = Convert.FromBase64String(EncryptedString)
            Return ASCIIEncoding.ASCII.GetString(DES.CreateDecryptor().TransformFinalBlock(buffer, 0, buffer.Length))
        Catch ex As Exception
            'MessageBox.Show("Invalid Key", "Decryption Failed!", MessageBoxButtons.OK, MessageBoxIcon.Exclamation)
            Return ""
        End Try
    End Function

    '#For Password only
    Public Function Get_MD5_Value(ByVal strText As String) As String

        Dim md5Value As String
        Dim generatedBytes() As Byte
        Dim originalBytes() As Byte

        'this is the full code to generate md5 
        Dim md5 As New MD5CryptoServiceProvider


        'convert string data to array of bytes
        originalBytes = ASCIIEncoding.Default.GetBytes(strText)

        'compute hash on generated byte array
        generatedBytes = md5.ComputeHash(originalBytes)

        'display hash bytes as readable string as the hash code generated will contain dash(-)
        ' to remove that Replace function of Regex is used here....
        md5Value = RegularExpressions.Regex.Replace(BitConverter.ToString(generatedBytes), "-", "")

        Return md5Value

    End Function
End Class
